### PR TITLE
Fix the definition of DVC pipeline sentence_embedding

### LINKED ISSUE #396: Fix the definition of pipelines/sentence_embedding/dvc.yaml
## 🐛 Bug description

The pipeline `sentence_embedding/dvc.yaml` is not correctly defined for `evaluation:deps`.

This creates the following issues:
  - The evaluation stage does not know how to pull the model `biobert_nli_sts_cord19_v1/`.
  - The training stage does not know it has to run before the evaluation stage for the models `tf_idf/` and `count/`.

## To reproduce

```
git checkout 12988ef564dd4e6373a7455f5ee30c0608e2e972
export PIPELINE=data_and_models/pipelines/sentence_embedding/dvc.yaml
dvc pull -d $PIPELINE
dvc repro -f $PIPELINE
```

This will give the error:
```
Running stage 'data_and_models/pipelines/sentence_embedding/dvc.yaml:evaluation@biobert_nli_sts_cord19_v1':
...
AttributeError: Path ../../models/sentence_embedding/biobert_nli_sts_cord19_v1/ not found
```

After manually pulling `biobert_nli_sts_cord19_v1`, this will give the error:
```
Running stage 'data_and_models/pipelines/sentence_embedding/dvc.yaml:evaluation@tf_idf':
...
FileNotFoundError: [Errno 2] No such file or directory: '../../models/sentence_embedding/tf_idf/model.pkl'
```

## Expected behavior

`dvc pull -d` and `dvc repro -f` should run without errors about missing files.

### PR DESCRIPTION
**Pull request by pafonta**
Fixes #396.

## Description

See #396 for the motivation behind the PR.

The solution from the PR (bc8f9cc24111841c15c2b1ee5c8daa2af0e86c1a):
1. separates the evaluation of the models we didn't train (new stage `evaluation_external`)
2. adds the model data as `deps` for each models we trained

Note:
The `cmd` field has been reformatted for better readability.

The dvc.lock has been updated (80b308c7d268f2411403a868865e2a7420aeb07b) and `dvc push` has been executed.

## How to test?

The following now works without error:
```
git clone --branch issue_396 https://github.com/BlueBrain/Search/
export PIPELINE=data_and_models/pipelines/sentence_embedding/dvc.yaml
dvc pull -d $PIPELINE
dvc repro -f $PIPELINE
```

## Checklist

- [x] This PR refers to an issue from the [issue tracker](https://github.com/BlueBrain/Search/issues).
- [x] Documentation and `whatsnew.rst` updated.
- [x] All CI tests pass.

### CODE REVIEW

**Review by EmilieDel — APPROVED** [review]
Thanks for doing this! I relaunch this and found the same results.

**Comment by pafonta** [comment]
- Resolved conflicts with `master`.
- Re-executed `dvc repro`.
- Committed updated `dvc.lock` in 8fb1fd7311902d8440d67c5bf7c39b18fe62a4b5.
- Re-executed `dvc push`.

**Review by Stannislav — APPROVED** [review]
Looks good to me!

So the crucial addition was the line
```
../../models/sentence_embedding/${item}
```
in `evaluation.deps`, right?

**Comment by pafonta** [comment]
Hello @Stannislav,

> So the crucial addition was the line
> 
> ```
> ../../models/sentence_embedding/${item}
> ```
> 
> in `evaluation.deps`, right?

Plus separating the evaluation of the models we didn't train (new stage `evaluation_external`) from the evaluation of the models we did train (existing stage `evaluation`).

**Pull request merged**
