### PR TITLE
Convert warnings to errors in unit tests

### LINKED ISSUE #401: Turn warnings in unit tests into errors
Our unit tests produce a substantial number of warnings. Should we take them more seriously and deal with them?

My personal view:
- warnings where it’s our fault: fix
- warnings where it’s a dependency’s fault: ignore explicitly

This way we would detect early if something we’re using is getting deprecated, and similar.
This can be done by turning warnings into errors. All can be configured in the in tox.ini .
It’s actually just a one-line change to insert error into filterwarnings:
```ini
[pytest]
testpaths = tests
filterwarnings =
    error
    ignore:Passing unrecoginized arguments to super:DeprecationWarning
```

Since filters [later in the list take precedence](https://docs.python.org/3/library/warnings.html#describing-warning-filters), all warnings will be converted into errors unless explicitly ignored by this list.

### PR DESCRIPTION
**Pull request by Stannislav**
Fixes #401.

## Description
See #401 

One might fix some of the warnings by upgrading third-party packages to higher versions.

## ~~Alternative solution~~ (see update below)
Instead of ignoring warnings globally one can ignore warnings on a one-by-one case using
- the `with warnings.catch_warnings()` context manager [[ref](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings)]
- the `@pytest.mark.filterwarnings` decorator for tests [[ref](https://docs.pytest.org/en/6.2.x/warnings.html#filterwarnings)]

Current approach (see update above)
- All warning filter configuration in one place, `tox.ini` (nice)
- Warning filters apply to all tests (not nice)
- So it's easy to manage warnings, check if they still hold etc, but might ignore too many warnings since they're applied globally

Alternative approach (see update above)
- Warning filters have to be placed exactly where the warning is raised (not so nice? cumbersome?)
- Warning filters are applied precisely to what is supposed to be ignored (nice)
- So we're sure we only ignore those warnings that we want, and not any other ones by accident. But finding back all warning filters placed in the tests could be more difficult (`grep` / `git grep` might help though)

## How to test?
All unit tests passing means no unhandled warnings are being raised.

To reproduce warnings coming from importing third-party modules, e.g. `docker`, run `python -We -c "import docker"`.

To locally reproduce an ignored warning edit the `filterwarnings` list in `tox.ini` and replace `ignore` by `error` in the respective warning.

## EDIT/UPDATE
- Our CI tests run `pip install '.[dev]'` and don't install  `requirements*.txt`
- Hence the locally installed dependency packages don't match the ones installed in CI most of the time
- Warnings seen locally don't appear in CI and vice versa
- To match the CI environment we need to upgrade the packages listed in `requirements*.txt`
- After upgrading many warnings coming from dependencies are fixed
- The remaining warnings coming from `docker` are now directly filtered in `conftest.py` instead of `tox.ini`.

## Checklist

- [x] This PR refers to an issue from the [issue tracker](https://github.com/BlueBrain/Search/issues).
  (if it is not the case, please create an issue first).
- [x] Unit tests added.
  (if needed)
- [ ] Documentation and `whatsnew.rst` updated.
  (if needed)
- [ ] `setup.py` and `requirements.txt` updated with new dependencies.
  (if needed)
- [ ] Type annotations added.
  (if a function is added or modified)
- [ ] All CI tests pass.

### CODE REVIEW

**Comment by Stannislav** [comment]
# To Discuss
- Upgrade of requirements (`requirements*.txt`)

**Review by EmilieDel — COMMENTED** [review]
Thanks for doing this @Stannislav, it is a great idea! 

I tried to run this PR on my personal laptop. 
I encountered an issue trying to `pip install -r requirements.txt`

```
ERROR: Cannot install -r requirements.txt (line 22) and spacy==3.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested spacy==3.1.0
    en-core-sci-lg 0.4.0 depends on spacy<3.1.0 and >=3.0.1
```

After removing temporarily `en-core-sci-lg` model, I tried to run the CI and encountered another issue:
```
ImportError while loading conftest '/Users/edelattr/Documents/Projects/BlueBrainSearch/code/tests/conftest.py'.
tests/conftest.py:29: in <module>
    import spacy
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/spacy/__init__.py:11: in <module>
    from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/thinc/api.py:2: in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/thinc/initializers.py:4: in <module>
    from .backends import Ops
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/thinc/backends/__init__.py:7: in <module>
    from .ops import Ops
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/thinc/backends/ops.py:10: in <module>
    from ..util import get_array_module, is_xp_array, to_numpy
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/thinc/util.py:36: in <module>
    import tensorflow.experimental.dlpack
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/__init__.py:41: in <module>
    from tensorflow.python.tools import module_util as _module_util
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/__init__.py:46: in <module>
    from tensorflow.python import data
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/__init__.py:25: in <module>
    from tensorflow.python.data import experimental
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/experimental/__init__.py:96: in <module>
    from tensorflow.python.data.experimental import service
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/experimental/service/__init__.py:140: in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py:25: in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py:20: in <module>
    from tensorflow.python.data.util import structure
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py:26: in <module>
    from tensorflow.python.data.util import nest
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/util/nest.py:41: in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/framework/sparse_tensor.py:29: in <module>
    from tensorflow.python.framework import constant_op
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:29: in <module>
    from tensorflow.python.eager import execute
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/eager/execute.py:27: in <module>
    from tensorflow.python.framework import dtypes
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:513: in <module>
    np.object,
../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/numpy/__init__.py:297: in __getattr__
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
E   DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
E   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
Is it expected ? I have the good version of `spacy` and `numpy` so I don't really understand why I have this!

**Comment by Stannislav** [comment]
> Thanks for doing this @Stannislav, it is a great idea!
> 
> I tried to run this PR on my personal laptop.
> I encountered an issue trying to `pip install -r requirements.txt`
> 
> ```
> ERROR: Cannot install -r requirements.txt (line 22) and spacy==3.1.0 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     The user requested spacy==3.1.0
>     en-core-sci-lg 0.4.0 depends on spacy<3.1.0 and >=3.0.1
> ```
> 
> After removing temporarily `en-core-sci-lg` model, I tried to run the CI and encountered another issue:
> 
> ```
> ImportError while loading conftest '/Users/edelattr/Documents/Projects/BlueBrainSearch/code/tests/conftest.py'.
> tests/conftest.py:29: in <module>
>     import spacy
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/spacy/__init__.py:11: in <module>
>     from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/thinc/api.py:2: in <module>
>     from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/thinc/initializers.py:4: in <module>
>     from .backends import Ops
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/thinc/backends/__init__.py:7: in <module>
>     from .ops import Ops
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/thinc/backends/ops.py:10: in <module>
>     from ..util import get_array_module, is_xp_array, to_numpy
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/thinc/util.py:36: in <module>
>     import tensorflow.experimental.dlpack
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/__init__.py:41: in <module>
>     from tensorflow.python.tools import module_util as _module_util
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/__init__.py:46: in <module>
>     from tensorflow.python import data
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/__init__.py:25: in <module>
>     from tensorflow.python.data import experimental
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/experimental/__init__.py:96: in <module>
>     from tensorflow.python.data.experimental import service
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/experimental/service/__init__.py:140: in <module>
>     from tensorflow.python.data.experimental.ops.data_service_ops import distribute
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py:25: in <module>
>     from tensorflow.python.data.experimental.ops import compression_ops
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py:20: in <module>
>     from tensorflow.python.data.util import structure
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py:26: in <module>
>     from tensorflow.python.data.util import nest
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/data/util/nest.py:41: in <module>
>     from tensorflow.python.framework import sparse_tensor as _sparse_tensor
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/framework/sparse_tensor.py:29: in <module>
>     from tensorflow.python.framework import constant_op
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:29: in <module>
>     from tensorflow.python.eager import execute
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/eager/execute.py:27: in <module>
>     from tensorflow.python.framework import dtypes
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:513: in <module>
>     np.object,
> ../../../../.pyenv/versions/3.7.5/envs/bluebrainsearch/lib/python3.7/site-packages/numpy/__init__.py:297: in __getattr__
>     warnings.warn(msg, DeprecationWarning, stacklevel=2)
> E   DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
> E   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> ```
> 
> Is it expected ? I have the good version of `spacy` and `numpy` so I don't really understand why I have this!

Interesting, I'll look into this!

**Comment by Stannislav** [comment]
@EmilieDel thanks for the nice catch, I must have missed it. There's no release of `en-core-sci-lg` that is compatible with `spacy==3.1.0` yet. I'll try and downgrade to `spacy==3.0.7`.

**Comment by Stannislav** [comment]
@EmilieDel I updated the requirements, and I think it works now.

In order to test one can do something like this:
```bash
(fresh-venv) $ pip install -r requirements.txt
(fresh-venv) $ pip install -r requirements-data_and_models.txt  # maybe not necessary
(fresh-venv) $ pip install -r requirements-dev.txt
(fresh-venv) $ pip install '.[dev]' --use-feature=in-tree-build
(fresh-venv) $ pytest
```

**Comment by EmilieDel** [comment]
Hello @Stannislav,

Thanks for addressing this! Starting from a fresh environment, everything seems to work fine! ☀️ 
Just a small detail, it seems the syntax `req @ URL` works only with `pip > 21.1`. i.e.
```bash
# in requirements.txt
en-core-sci-lg @ https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz
# in requirements-dev.txt
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0.tar.gz
```
Should we specify this somewhere ? Maybe in the `pyproject.toml` ?

**Comment by Stannislav** [comment]
> Hello @Stannislav,
> 
> Thanks for addressing this! Starting from a fresh environment, everything seems to work fine! ☀️
> Just a small detail, it seems the syntax `req @ URL` works only with `pip > 21.1` (from [here](https://pip.pypa.io/en/stable/news/#v21-1)). i.e.
> 
> ```shell
> # in requirements.txt
> en-core-sci-lg @ https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz
> # in requirements-dev.txt
> en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0.tar.gz
> ```
> 
> Should we specify this somewhere ? Maybe in the `pyproject.toml` ?

Nice! Thanks for testing!

But regarding `req @ URL`, I have the impression it was introduced in `10.0` [[ref](https://pip.pypa.io/en/stable/news/#b1-2018-03-31)]. If I'm reading it correctly, in the version you mentioned they introduced the `--use-feature=in-tree-build` flag + fixed some bugs related to the `req @ URL` syntax. Could you maybe double check if that's correct?

**Comment by EmilieDel** [comment]
I tried with `pip==19.0.3` and got this issue: 
```
Requirement 'en-core-sci-lg @ https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz' looks like a filename, but the file does not exist
Processing ./en-core-sci-lg @ https:/s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/Users/edelattr/Documents/Projects/BlueBrainSearch/code/en-core-sci-lg @ https:/s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz'

You are using pip version 19.0.3, however version 21.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
But you are right, it is a bug fix. I don't what is the best strategy in those cases.

**Comment by Stannislav** [comment]
> I tried with `pip==19.0.3` and got this issue:
> 
> ```
> Requirement 'en-core-sci-lg @ https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz' looks like a filename, but the file does not exist
> Processing ./en-core-sci-lg @ https:/s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz
> Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/Users/edelattr/Documents/Projects/BlueBrainSearch/code/en-core-sci-lg @ https:/s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz'
> 
> You are using pip version 19.0.3, however version 21.2.2 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> ```
> 
> But you are right, it is a bug fix. I don't what is the best strategy in those cases.

Wow, weird. I can reproduce this. Seems like a bug in pip as it misinterprets the HTTP URL as a local path.

Here's a stupid fix I came up with by trial and error: add a "?" at the end of the URL (`.../v0.4.0/en_core_sci_lg-0.4.0.tar.gz?'). Seems like with that pip interprets it correctly as a web URL.

Can you maybe give it a try if it works for you too?

Not sure what we should do about this. Options:
- Restricting to higher pip version in `pyproject.toml` like you suggested (maybe too restrictive?)
- Adding question marks like in the fix above (too weird-looking?)

Anyway, maybe someone else has a better idea.

**Comment by EmilieDel** [comment]
> Can you maybe give it a try if it works for you too?
Adding a question mark is also working for me! 

I am sure either what is the best solution.

**Comment by FrancescoCasalegno** [comment]
Looks all good! Let's just wait for #391 to be merged and then we can merge this into `master` as well!

**Pull request merged**
