### PR TITLE
#385 Huggingface tokenizer provides incorrect model_max_length

### LINKED ISSUE #385: Huggingface tokenizer provides incorrect model_max_length
## 🐛 Bug description

During the creation of the `mining_cache`, an issue was raised:
```
Article ID: 2951
Traceback (most recent call last):
  File "/raid/users/edelattr/Search/src/bluesearch/database/mining_cache.py", line 146, in work_loop
    self._mine(article_id)
  File "/raid/users/edelattr/Search/src/bluesearch/database/mining_cache.py", line 199, in _mine
    texts=texts, model_entities=self.model, models_relations={}, debug=True
  File "/raid/users/edelattr/Search/src/bluesearch/mining/pipeline.py", line 116, in run_pipeline
    for doc, metadata in docs_gen:
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/language.py", line 1451, in pipe
    for doc, context in zip(docs, contexts):
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/language.py", line 1484, in pipe
    for doc in docs:
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/util.py", line 1484, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy/pipeline/pipe.pyx", line 53, in pipe
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/util.py", line 1484, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy/pipeline/transition_parser.pyx", line 189, in pipe
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/util.py", line 1439, in minibatch
    batch = list(itertools.islice(items, int(batch_size)))
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/util.py", line 1484, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy/pipeline/pipe.pyx", line 53, in pipe
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/util.py", line 1484, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy_transformers/pipeline_component.py", line 204, in pipe
    self.set_annotations(subbatch, self.predict(subbatch))
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy_transformers/pipeline_component.py", line 220, in predict
    activations = self.model.predict(docs)
  File "/home/edelattr/.local/lib/python3.7/site-packages/thinc/model.py", line 312, in predict
    return self._func(self, X, is_train=False)[0]
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy_transformers/layers/transformer_model.py", line 142, in forward
    tensors, bp_tensors = transformer(wordpieces, is_train)
  File "/home/edelattr/.local/lib/python3.7/site-packages/thinc/model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/edelattr/.local/lib/python3.7/site-packages/thinc/layers/pytorchwrapper.py", line 80, in forward
    Ytorch, torch_backprop = model.shims[0](Xtorch, is_train)
  File "/home/edelattr/.local/lib/python3.7/site-packages/thinc/shims/pytorch.py", line 29, in __call__
    return self.predict(inputs), lambda a: ...
  File "/home/edelattr/.local/lib/python3.7/site-packages/thinc/shims/pytorch.py", line 38, in predict
    outputs = self._model(*inputs.args, **inputs.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/bert/modeling_bert.py", line 964, in forward
    past_key_values_length=past_key_values_length,
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/bert/modeling_bert.py", line 206, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (551) must match the size of tensor b (512) at non-singleton dimension 1
```

This was also found and described on `spacy` github repo: https://github.com/explosion/spaCy/discussions/7393

## To reproduce

1. `dvc pull` last version of `ner_er` models
2. Run this code
```python
from bluesearch.mining import run_pipeline
from bluesearch.sql import retrieve_articles
import spacy

article_ids = [3707,]
all_texts = retrieve_articles(article_ids, bbs_mysql_engine)

spacy_model = spacy.load(path)
for i, row in all_texts.iterrows():
    run_pipeline([(row.text, {"article_id": row.article_id})], spacy_model, {})
```

## Expected behavior

We should find a way to fix the `model_max_length`:
- Either at the tokenizer level
- Either at the spacy `config.cfg` level.

## Environment

Please provide the following information.

 - Blue Brain Search version (use `python -c "import bluesearch; print(bluesearch.__version__)"`): 0.1.3.dev25
 - OS (e.g., Linux): Linux
 - How you installed Blue Brain Search (source, pip, ...): pip
 - Python version (use `python -V`): Python 3.7.5

### PR DESCRIPTION
**Pull request by EmilieDel**
Fixes #385.

## Description

During the creation of the mining_cache, an issue was raised (check the issue #385). Several possibilities to handle this issue were considered (on spaCy and transformers side).
Proposed solution: Modify initial `config.cfg` before training the NER models.

If everyone agrees with this way of handling the issue, 
- [x] Relaunch `dvc repro` 
- [x] Update `dvc.lock`

## Checklist

- [X] This PR refers to an issue from the [issue tracker](https://github.com/BlueBrain/Search/issues).
  (if it is not the case, please create an issue first).
- [X] Unit tests added.
  (if needed)
- [x] Documentation and `whatsnew.rst` updated.
  (if needed)
- [X] `setup.py` and `requirements.txt` updated with new dependencies.
  (if needed)
- [X] Type annotations added.
  (if a function is added or modified)
- [x] All CI tests pass.

### CODE REVIEW

**Review by Stannislav — APPROVED** [review]
Nice, I don't see anything wrong with this off the top of my head.

Like you @EmilieDel and @pafonta already discussed in #385 one will probably need to `dvc repro` to see if the output changes. Otherwise it's looking good to me.

**Review by pafonta — APPROVED** [review]
Thank you for fixing this!

LGTM!

**Comment by pafonta** [comment]
Hello @EmilieDel,

I think `dvc push` was not executed yet.

I have tried `dvc pull` and it failed on the `models/ner`/ and `models/ner_er/`.

**Comment by EmilieDel** [comment]
> Hello @EmilieDel,
I think dvc push was not executed yet.
I have tried dvc pull and it failed on the models/ner/ and models/ner_er/.

Yes sorry, I didn't have the time this morning to do it. It should be done now.  

It took the opportunity to check the `config.cfg` of the models. Now we have a new section:
```
[components.transformer.model.tokenizer_config]
model_max_length = 512
use_fast = true
```
It seems it is working fine 🎉

**Comment by pafonta** [comment]
The configuration model_max_length = 512 is indeed now in the `config.cfg` files, both in `models/ner/` and `models/ner_er/`. Is it also in the `transformer/model/tokenizer_config.json` files.

**Comment by pafonta** [comment]
➡️ The truncation on token length is now applied after a `spacy.load()`.

The steps from #385 (see below) to reproduce the issue are now passing without errors:

> 1. `dvc pull` last version of `ner_er` models
> 2. Run this code
> 
> ```python
> from bluesearch.mining import run_pipeline
> from bluesearch.sql import retrieve_articles
> import spacy
> 
> article_ids = [3707,]
> all_texts = retrieve_articles(article_ids, bbs_mysql_engine)
> 
> spacy_model = spacy.load(path)
> for i, row in all_texts.iterrows():
>     run_pipeline([(row.text, {"article_id": row.article_id})], spacy_model, {})
> ```

**Comment by pafonta** [comment]
⚠️ Do we try somewhere to match indices before and after the texts went trough the model?

Indeed, now, the two lists of indices would not match any more when the token length is more than 512.

When truncation is applied, there is this warning:

> Token indices sequence length is longer than the specified maximum sequence length for this model (641 > 512). Running this sequence through the model will result in indexing errors.

**Pull request merged**
