### PR TITLE
Run CI on mac OS

### PR DESCRIPTION
**Pull request by EmilieDel**
## Suggestion

Add `mac-os` in the CI.

## How to test?

Please provide here instructions on how to test the changes introduced by this PR.
(if some changes cannot be tested by automated tests)

## Checklist

- [x] This PR refers to an issue from the [issue tracker](https://github.com/BlueBrain/Search/issues).
  (if it is not the case, please create an issue first).
- [X] Unit tests added.
  (if needed)
- [X] Documentation and `whatsnew.rst` updated.
  (if needed)
- [X] `setup.py` and `requirements.txt` updated with new dependencies.
  (if needed)
- [X] Type annotations added.
  (if a function is added or modified)
- [x] All CI tests pass.

### CODE REVIEW

**Review by Stannislav — APPROVED** [review]
Nice, thanks :)

**Review by jankrepl — APPROVED** [review]
Great!!!

**Comment by FrancescoCasalegno** [comment]
Thanks for this!

### Question

What is the reason for adding tests for Mac OS? 
Is it because we want to support this operating system from now on? If that's the reason, maybe we can add the classifier `Operating System :: MacOS` to our list in the `setup.py`:
https://github.com/BlueBrain/Search/blob/059c2a342284e77fa2ff8d1a0a6c596ee4ad7076/setup.py#L34

**Comment by EmilieDel** [comment]
Thanks for the feedback @FrancescoCasalegno. I think it is interesting to support Mac OS as we develop partially on this operating system anyway. 

Good idea, I will add this classifier in our `setup.py`.

**Comment by FrancescoCasalegno** [comment]
Another element to consider is whether adding theses checks will signficantly impact the tests runtime.
I am reporting here the runtimes of [this run](https://github.com/BlueBrain/Search/actions/runs/914890140).

| Test | Runtime |
|:------------- |:-----|
| ci testing / run_test (ubuntu-latest, 3.7) | 7m |
| ci testing / run_test (ubuntu-latest, 3.8) | 3m |
| ci testing / run_test (ubuntu-latest, 3.9) | 3m |
| ci testing / run_test (macos-latest, 3.7) | 11m |
| ci testing / run_test (macos-latest, 3.8) | 6m |
| ci testing / run_test (macos-latest, 3.9) | 10m |

1. Any idea why Mac OS X tests runtimes are ~2x slower than Ubuntu?
2. I would imagine that GitHub Actions has limitations in terms of how many tests can be run in parallel. Currently we can still run all our tests in parallel, but do we know what are the limits?

**Comment by EmilieDel** [comment]
1. There is one more step `brew install mysql` for MacOS which is taking ~ 1-2 mins. Otherwise, it seems there are some seconds more for each step, but nothing really major. 
2. [Here](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration) are some info about usage limits. The part related to this PR is:
image

I totally see your points. If you think it is an overkill, I don't mind closing this PR!

**Review by FrancescoCasalegno — APPROVED** [review]
LGTM, thanks again @EmilieDel for addressing my comments!

By looking at runtimes [here](https://github.com/BlueBrain/Search/actions/runs/982005745) it seems that overall the CI went from taking ~8m to ~11m.  So the CI is now ~35% slower, but I think it is fine. If in the future we feel it's too slow, we can try to optimize certain things or skip some tests.

One way to do that could be to run the extensive tests including `lint`, `docs`, `package` only if the OS is Ubuntu **and** the Python version is 3.7. So basically replace 
https://github.com/BlueBrain/Search/blob/059c2a342284e77fa2ff8d1a0a6c596ee4ad7076/.github/workflows/run-tests.yml#L53
by
```yaml
if: matrix.python-version == '3.7' && matrix.os == 'ubuntu-latest'
```

So feel free to merge @EmilieDel ! 👍

**Pull request merged**
