### PR TITLE
Re-run DVC pipelines to release v0.2.0

### LINKED ISSUE #394: 🚀 Release v0.2.0
The [milestone for releasing `v0.2.0`](https://github.com/BlueBrain/Search/milestone/1) is complete.

## Actions
- [x] Re-run all DVC stuff.
- [x] Add new tag `v0.2.0`.
- [ ] Merge into `master`.
- [ ] Check that RTD successfully builds a new `stable` version of the `docs`.
- [ ] Upload new tag on PyPI.

### PR DESCRIPTION
**Pull request by pafonta**
Fixes #394.

➡️ READY TO BE MERGED

## Description

- [x] Add the new tag v0.2.0 to `git`.
- [x]  Add the new tag v0.2.0 to each `Dockerfile` for each DVC pipeline.
- [x] Update `whatsnew.rst`, including adding the release date.
- Re-run all DVC pipelines with latest master 12988ef564dd4e6373a7455f5ee30c0608e2e972 (this includes #388):
  - [x] sentence_embedding
  - [x] ner
- Update the `dvc.lock` of all the DVC pipelines:
  - [x] sentence_embedding
  - [x] ner

## Test

This

```
git checkout v0.2.0
dvc pull
dvc repro --recursive .
```

should finish with

```
Data and pipelines are up to date.
```

#### Metrics

For all Transformer-based models and with a precision of `more than 10e-6`, the `pearson_r` has changed. Otherwise, for other models, a lower precision, or other metrics, there is no change.

#### Models

The `sentence_embedding/tf_idf/` model has changed.

As the metrics did not change for this model, we could assume that the binary change for this model comes from the modification in `train.py`:

```
git diff v0.1.1 v0.2.0 -- data_and_models/pipelines/sentence_embedding/train.py
```

#### Metrics

The scores has changed for `DISEASE`, -1.11 % (relative):

| Path                    | Metric           | Old    | New    | Change   |
|-------------------------|------------------|--------|--------|----------|
| disease.json            | entity_f1-score  | 0.7147 | 0.7068 | -0.0079  |
| disease.json            | entity_precision | 0.6976 | 0.6939 | -0.0037  |
| disease.json            | entity_recall    | 0.7327 | 0.7201 | -0.0126  |
| disease.json            | token_f1-score   | 0.7764 | 0.772  | -0.0044  |
| disease.json            | token_precision  | 0.7522 | 0.7504 | -0.0017  |
| disease.json            | token_recall     | 0.8022 | 0.7948 | -0.0074  |
| interrater/disease.json | entity_f1-score  | 0.7346 | 0.7226 | -0.012   |
| interrater/disease.json | entity_precision | 0.6586 | 0.6478 | -0.0108  |
| interrater/disease.json | entity_recall    | 0.8305 | 0.8169 | -0.0136  |

#### Models

All models have changed MD5 sum but not size.

This behaviour should have been fixed by PR #359, according to https://github.com/BlueBrain/Search/issues/343#issuecomment-848226484. However, PR #359 was closed without a follow-up. Then, there is no fix today for this behaviour in `master`. There is no plan for it ever, it seems.

## Fixed issues

The argument `etypes` was removed from `pipelines/ner/add_er.py` in #366 but not from `pipelines/ner/dvc.yaml`.
This made the `ner` pipeline fail.
Fixed in 759b81378a27bd7fcdb6c2bd697b6215f461bedf.

The indirect dependency of `pipeline/ner/dvc.yaml:train` to `biobert_nli_sts_cord19_v1/` was missing.
This required to do a manual `dvc pull` for the model.
Added in c2796f68b44babaacaa2eeb766e5a464acdb6587.

## Checklist

- [x] This PR refers to an issue from the [issue tracker](https://github.com/BlueBrain/Search/issues).
- [x] Documentation and `whatsnew.rst` updated.
- [x] All CI tests pass. 

## Uncovered issues

The pipeline `sentence_embedding/dvc.yaml` is not correctly defined for `evaluation:deps`.
➡️ Dedicated issue created: #396.

The Documentation and Tracker links on PyPI are internal links (not public to people external to BBP).
➡️ Dedicated issue created: #397.

### CODE REVIEW

**Comment by FrancescoCasalegno** [comment]
> The Documentation and Tracker links on PyPI are internal links (not public to people external to BBP).

Nice catch! I tried to fix it now in #400. Maybe we can merge that fix before before releasing this `0.2.0`.

**Comment by EmilieDel** [comment]
> The argument etypes was removed from pipelines/ner/add_er.py in #366 but not from pipelines/ner/dvc.yaml.
This made the ner pipeline fail.
Fixed in 759b813.

Nice finding! I was planning to fix that. Thanks for handling this in the current PR!

**Comment by FrancescoCasalegno** [comment]
Thank for this work @pafonta !

I think that there are absolute paths written in some output files that prevent 100% binary reproducibility of the results...
```bash
$ Search/data_and_models/models# grep -rIn  fonta

language_modeling/biobert_cord19_v1/trainer_state.json:3:  "best_model_checkpoint": "/raid/users/fonta/bbs/models/biobert_v1.1_pubmed_nli_sts_cord19_v6_bis/checkpoint-595000",
ner_er/model-chemical/transformer/model/config.json:2:  "_name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-chemical/model-best/transformer/model",
ner_er/model-chemical/transformer/model/tokenizer_config.json:1:{"do_lower_case": true, "unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]", "tokenize_chinese_chars": true, "strip_accents": null, "special_tokens_map_file": "./models/cache/98949237170dd1127509c8034c704072bdfa28b8dc8032e4e2aa43129f47b8bb.275045728fbf41c11d3dae08b8742c054377e18d92cc7b72b6351152a99b64e4", "name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-chemical/model-best/transformer/model", "do_basic_tokenize": true, "never_split": null}
ner_er/model-cell_type/transformer/model/config.json:2:  "_name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-cell_type/model-best/transformer/model",
ner_er/model-cell_type/transformer/model/tokenizer_config.json:1:{"do_lower_case": true, "unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]", "tokenize_chinese_chars": true, "strip_accents": null, "special_tokens_map_file": "./models/cache/98949237170dd1127509c8034c704072bdfa28b8dc8032e4e2aa43129f47b8bb.275045728fbf41c11d3dae08b8742c054377e18d92cc7b72b6351152a99b64e4", "name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-cell_type/model-best/transformer/model", "do_basic_tokenize": true, "never_split": null}
ner_er/model-protein/transformer/model/config.json:2:  "_name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-protein/model-best/transformer/model",
ner_er/model-protein/transformer/model/tokenizer_config.json:1:{"do_lower_case": true, "unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]", "tokenize_chinese_chars": true, "strip_accents": null, "special_tokens_map_file": "./models/cache/98949237170dd1127509c8034c704072bdfa28b8dc8032e4e2aa43129f47b8bb.275045728fbf41c11d3dae08b8742c054377e18d92cc7b72b6351152a99b64e4", "name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-protein/model-best/transformer/model", "do_basic_tokenize": true, "never_split": null}
ner_er/model-pathway/transformer/model/config.json:2:  "_name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-pathway/model-best/transformer/model",
ner_er/model-pathway/transformer/model/tokenizer_config.json:1:{"do_lower_case": true, "unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]", "tokenize_chinese_chars": true, "strip_accents": null, "special_tokens_map_file": "./models/cache/98949237170dd1127509c8034c704072bdfa28b8dc8032e4e2aa43129f47b8bb.275045728fbf41c11d3dae08b8742c054377e18d92cc7b72b6351152a99b64e4", "name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-pathway/model-best/transformer/model", "do_basic_tokenize": true, "never_split": null}
ner_er/model-organism/transformer/model/config.json:2:  "_name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-organism/model-best/transformer/model",
ner_er/model-organism/transformer/model/tokenizer_config.json:1:{"do_lower_case": true, "unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]", "tokenize_chinese_chars": true, "strip_accents": null, "special_tokens_map_file": "./models/cache/98949237170dd1127509c8034c704072bdfa28b8dc8032e4e2aa43129f47b8bb.275045728fbf41c11d3dae08b8742c054377e18d92cc7b72b6351152a99b64e4", "name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-organism/model-best/transformer/model", "do_basic_tokenize": true, "never_split": null}
ner_er/model-cell_compartment/transformer/model/config.json:2:  "_name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-cell_compartment/model-best/transformer/model",
ner_er/model-cell_compartment/transformer/model/tokenizer_config.json:1:{"do_lower_case": true, "unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]", "tokenize_chinese_chars": true, "strip_accents": null, "special_tokens_map_file": "./models/cache/98949237170dd1127509c8034c704072bdfa28b8dc8032e4e2aa43129f47b8bb.275045728fbf41c11d3dae08b8742c054377e18d92cc7b72b6351152a99b64e4", "name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-cell_compartment/model-best/transformer/model", "do_basic_tokenize": true, "never_split": null}
ner_er/model-disease/transformer/model/config.json:2:  "_name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-disease/model-best/transformer/model",
ner_er/model-disease/transformer/model/tokenizer_config.json:1:{"do_lower_case": true, "unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]", "tokenize_chinese_chars": true, "strip_accents": null, "special_tokens_map_file": "./models/cache/98949237170dd1127509c8034c704072bdfa28b8dc8032e4e2aa43129f47b8bb.275045728fbf41c11d3dae08b8742c054377e18d92cc7b72b6351152a99b64e4", "name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-disease/model-best/transformer/model", "do_basic_tokenize": true, "never_split": null}
ner_er/model-drug/transformer/model/config.json:2:  "_name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-drug/model-best/transformer/model",
ner_er/model-drug/transformer/model/tokenizer_config.json:1:{"do_lower_case": true, "unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]", "tokenize_chinese_chars": true, "strip_accents": null, "special_tokens_map_file": "./models/cache/98949237170dd1127509c8034c704072bdfa28b8dc8032e4e2aa43129f47b8bb.275045728fbf41c11d3dae08b8742c054377e18d92cc7b72b6351152a99b64e4", "name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-drug/model-best/transformer/model", "do_basic_tokenize": true, "never_split": null}
ner_er/model-organ/transformer/model/config.json:2:  "_name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-organ/model-best/transformer/model",
ner_er/model-organ/transformer/model/tokenizer_config.json:1:{"do_lower_case": true, "unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]", "tokenize_chinese_chars": true, "strip_accents": null, "special_tokens_map_file": "./models/cache/98949237170dd1127509c8034c704072bdfa28b8dc8032e4e2aa43129f47b8bb.275045728fbf41c11d3dae08b8742c054377e18d92cc7b72b6351152a99b64e4", "name_or_path": "/raid/users/fonta/prs/issue_394/Search-ner/data_and_models/pipelines/ner/../../models/ner/model-organ/model-best/transformer/model", "do_basic_tokenize": true, "never_split": null}
```

**Comment by pafonta** [comment]
Hello @FrancescoCasalegno,

> Things seem to be fine for the Sentence Embedding pipeline, but for NER I think that there are absolute paths written in some output files that prevent 100% binary reproducibility of the results...
> 
> [...]
> 
> Other than that everything seems to be fine, and I was able to get the same `sha`s you did for the `ner/` models 🙂 So the problem for me is just about the `ner_er/`.

Is the issue caused by `add_er.py` then?

The problematic field `name_or_path` seems added by `add_er.py` if the models in `ner/ `do nor have it.

**Comment by pafonta** [comment]
As discussed, I have investigated the issue.

The issue is about having an `absolute` path under `transformer/model/` in both `config.json` and `tokenizer_config.json`.

The issue is coming from `add_er.py`. Indeed, there is no such issue in `models/ner/*`, only in `models/ner_er/*`.

The issue was already there `before` the current PR. It seems #343 missed to identify the issue.

The issue is caused by some code in the `transformers` library when spaCy delegates the saving to it:

- here for `transformer/model/config.json`:
https://github.com/explosion/spacy-transformers/blob/7681ec22e827b4f873f7e348d356505d2a920492/spacy_transformers/pipeline_component.py#L369

- and here for `transformer/model/tokenizer_config.json`:
https://github.com/explosion/spacy-transformers/blob/7681ec22e827b4f873f7e348d356505d2a920492/spacy_transformers/pipeline_component.py#L366

**Comment by pafonta** [comment]
Hello @FrancescoCasalegno,

The absolute paths in `models/ner_er/` are now gone.

The solution has been implemented in 90b5ff1847f90eaabbcf3a522151106643463efb.
`dvc.lock` has been updated in 58436ec3ca35bfde4d15bafede70459fca821065.

The `v0.2.0` tag have been moved to HEAD of the PR branch.
`dvc push` has been executed.

**Is there something else you would like to be done before merging?**

**Review by FrancescoCasalegno — APPROVED** [review]
Thanks a lot for taking care of this @pafonta !
LGTM!

**Review by EmilieDel — APPROVED** [review]
Thanks for doing this @pafonta!

**Pull request merged**
