### PR TITLE
Upgrade to dvc>=2  + release bluesearch v0.1.1

### LINKED ISSUE #273: Upgrade to dvc 2.x
## 🚀 Feature

- [ ] Add `dvc>=2.0` to our dependencies.
- [ ] Check that `.dvc` files generated for the corresponding data files are still valid with `dvc>=2.0`. 
- [ ] Re-run our pipelines in `data_and_models` and check that the only difference produced using `dvc>=2.0` is in the format of the `.lock` files, but not in the `md5` sums.
- [ ] Release a new tag for `BlueBrain/Search`.

## Motivation

[DVC released their 2.0](https://dvc.org/blog/dvc-2-0-release) and backward compatibility of the new updates with the old 1.x versions is now broken.

### PR DESCRIPTION
**Pull request by FrancescoCasalegno**
Fixes #273.

## Description

Upgrades to `dvc==2.0.6` and releases `bluesearch v0.1.1`.

### Notes
1. I used to consistently get the error 
```ValueError: unsupported pickle protocol: 5```
 when trying to `dvc pull` or `dvc add` using `dvc>=2` in a directory where I still had the old cache generated using `dvc<2`. But for some reason I cannot reproduce the error any more! 🤷  Anyway, should you see that error, try to `rm -rf .dvc/cache` and then re-populate your cache with a `dvc pull` (or `dvc fetch`)—this worked for me.
 2. The new `dvc.lock` format is only slightly different but breaks backward compatibility. Also, `git diff` is confused by the new format, so please see "How to test" below to see how to visualize the changes.
3. Here are some highlights of the new elemnents introduced in `dvc 2.0`.
    1. [**ML experiments**](https://dvc.org/blog/dvc-2-0-release#lightweight-ml-experiments) (beta, may change) lets you try various hyper-parameter configurations in a lightweight way, without having to create a `git branch` for each of them.
    2. [ **`dvc run` deprecated in favor of `dvc stage add`**](https://dvc.org/blog/dvc-2-0-release#ml-model-checkpoints-versioning).
    3. [**Better metrics log and viz**](https://dvc.org/blog/dvc-2-0-release#metrics-logging).

## How to test?
1. To see what _really_ changed in any of the two `dvc.lock` files, other than the new format, please run the following command.
```bash
cp dvc.lock dvc_new.lock
git checkout master -- dvc.lock
vimdiff dvc.lock <(sed "s/^..//" dvc_new.lock | tail -n +3 | cat)  # fix formatting to allow comparison!
```
2. Follow the same steps of "How To Test" from #265, just replacing `v0.1.0` with `v0.1.1`.
## Checklist

- [x] This PR refers to an issue from the [issue tracker](https://github.com/BlueBrain/Search/issues).
  (if it is not the case, please create an issue first).
- [x] Documentation and `whatsnew.rst` updated.
  (if needed)
- [x] `setup.py` and `requirements.txt` updated with new dependencies.
  (if needed)
- [x] All CI tests pass.

### CODE REVIEW

**Review by pafonta — COMMENTED** [review]
Thank you for doing this!
I cannot wait to use the new features from DVC 2 🔥

I have found the following, which might show something wrong, isn't it?
After reproducing a pipeline, I have got a `git diff` output on `dvc.lock` while I shouldn't:

```
diff --git a/data_and_models/pipelines/ner/dvc.lock b/data_and_models/pipelines/ner/dvc.lock
index 84ba18d..90df6b1 100644
@@ -24,6 +24,8 @@ stages:
     outs:
     - path: ../../models/ner/model1
       md5: 4c687b7dd44d0f7adc2d3df2e2e4f624.dir
+      size: 100181750
+      nfiles: 16
   train_model2:
```

Here is how to reproduce:

```
git checkout dvc_2.0

docker build <options> -f data_and_models/pipelines/ner/Dockerfile -t <image> .
docker run -it -rm <options> --name <container> <image>

cd data_and_models/pipelines/ner/
dvc repro -f eval_disease
git diff dvc.lock
```

**Comment by FrancescoCasalegno** [comment]
> Thank you for doing this!
> I cannot wait to use the new features from DVC 2 🔥
> 
> I have found the following, which might show something wrong, isn't it?
> After reproducing a pipeline, I have got a `git diff` output on `dvc.lock` while I shouldn't:

Hello @pafonta and thanks for your review!
I tried to follow your exact instructions (while also adding a `dvc pull` to get the annotation input files) but couldn't reproduce your results. That is, I still got the same `dvc.lock` I had before!

**Review by EmilieDel — APPROVED** [review]
Really nice work 🎉 

I did the `How to test` section for the `ner` pipeline and it worked fine. I also tried to reproduce the code from @pafonta and I do not have differences in the `dvc.lock` file after doing `dvc repro -f eval_disease`.

**Comment by jankrepl** [comment]
After cleaning my cache and just trying to `dvc pull` I get the following error.
```
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
data_and_models/metrics/sentence_embedding/sbiobert.csv
data_and_models/metrics/sentence_embedding/sbiobert.json
data_and_models/metrics/sentence_embedding/biobert_nli_sts_cord19_v1.csv
data_and_models/metrics/sentence_embedding/biobert_nli_sts_cord19_v1.json
data_and_models/metrics/sentence_embedding/biobert_nli_sts.csv
data_and_models/metrics/sentence_embedding/biobert_nli_sts.json
data_and_models/metrics/sentence_embedding/sbert.csv
data_and_models/metrics/sentence_embedding/sbert.json
```

Did you maybe forget to push them to remote @FrancescoCasalegno? Or was it done on purpose and the only way we can get them is to recreate them? I vaguely remember that we agreed on the "push all assets to remote" strategy, didn't we?

**Comment by EmilieDel** [comment]
I have the same warning error as @jankrepl. 

> ERROR: failed to pull data from the cloud - Checkout failed for following targets:
../../metrics/sentence_embedding/biobert_nli_sts_cord19_v1.csv
../../metrics/sentence_embedding/biobert_nli_sts_cord19_v1.json
../../metrics/sentence_embedding/sbert.csv
../../metrics/sentence_embedding/sbert.json
../../metrics/sentence_embedding/sbiobert.csv
../../metrics/sentence_embedding/sbiobert.json
../../metrics/sentence_embedding/biobert_nli_sts.csv
../../metrics/sentence_embedding/biobert_nli_sts.json

**Comment by Stannislav** [comment]
Does anyone know what's up with this error? I get it on the DVC docker containers when I `dvc pull`:
```
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
data_and_models/metrics/sentence_embedding/biobert_nli_sts.csv
data_and_models/metrics/sentence_embedding/biobert_nli_sts.json
data_and_models/metrics/sentence_embedding/sbert.csv
data_and_models/metrics/sentence_embedding/sbert.json
data_and_models/metrics/sentence_embedding/sbiobert.csv
data_and_models/metrics/sentence_embedding/sbiobert.json
data_and_models/metrics/sentence_embedding/biobert_nli_sts_cord19_v1.csv
data_and_models/metrics/sentence_embedding/biobert_nli_sts_cord19_v1.json
Is your cache up to date?
<https://error.dvc.org/missing-files>
```

**Review by Stannislav — APPROVED** [review]
I ran `dvc repro` on both the `ner` and the `sentemb` containers and they didn't produce a diff.

`git diff` gave a huge list of diffs in `tests`, `docs`, and `notebook`, I had to check them out manually to see that there are no diffs in `data_and_models`.

**Comment by pafonta** [comment]
Hello @FrancescoCasalegno!

I have tried again from scratch. I still get the diff on `dvc.lock` as in https://github.com/BlueBrain/Search/pull/311#pullrequestreview-619580962. I have tried with the new HEAD (1a72e8c8b5eff09c4ed47e9b01b54362b7c0c916).

@EmilieDel and @Stannislav, are you trying from scratch? This is the only way to actually check.

Here are the step-by-step instructions:

```
git clone https://github.com/BlueBrain/Search
cd Search/
git checkout dvc_2.0

cp /<path to prodigy>/prodigy-1.10.7-cp36.cp37.cp38-cp36m.cp37m.cp38-linux_x86_64.whl .

docker build -f data_and_models/pipelines/ner/Dockerfile -t <image> .
docker run -it --rm -v /raid:/raid --gpus all --name <container> <image>

dvc remote modify gpfs_ssh ask_password true
dvc remote modify gpfs_ssh user <user>

dvc pull data_and_models/annotations/ner/*.dvc
cd data_and_models/pipelines/ner/
dvc repro -f eval_disease
git diff
```

**Comment by EmilieDel** [comment]
Yes I tried from scratch (I even cloned the repo again, so my `dvc cache` was empty).

**Comment by FrancescoCasalegno** [comment]
@jankrepl  @EmilieDel you are right, I forgot to `dvc push` these outputs. It should now be done, could you please check now if it works?

**Review by jankrepl — APPROVED** [review]
I guess it LGMT. 

The current process that one needs to go through to verify whether everything works is really time consuming. 

Please check https://github.com/BlueBrain/Search/issues/288#issuecomment-808163633 where I tried to propose a solution.

**Pull request merged**
