### PR TITLE
[BBS-233] Remove Sent2Vec

### PR DESCRIPTION
**Pull request by FrancescoCasalegno**
## Description

Same goal as #244, i.e. making code `python 3.9`-compatible, but achieve that by getting rid of `sent2vec` and `bsv`.

Fixes BBS-233. 
Closes #244.

## Todo
- [x] remove `sent2vec` and `bsv` from `src/`
- [x] remove `sent2vec` and `bsv` from `setup.py` etc.
- [x] remove `sent2vec` and `bsv` from `tests/` and `benchmarks/`
- [x] remove `sent2vec` and `bsv` from `notebooks/`

## Checklist:

- [x] This PR refers to an issue present in the [issue tracker](https://github.com/BlueBrain/Search/issues
) (if it is not the case, please create an issue
 first).
- [x] Unit tests added.
- [x] Documentation and `whatsnew.rst` updated (if needed).
- [x] `setup.py` and `requirements.txt` updated with new dependencies.
- [x] Travis CI pipeline run (add `[test travis]` to your git commit to run it)
- [x] Restore Travis CI `travis.yaml` file

### CODE REVIEW

**Review by pafonta — COMMENTED** [review]
Hello @FrancescoCasalegno !

I would be against removing `notebooks/STS_evaluation.ipynb`.

Indeed, we need this notebook to adapt what we did for CORD-19 to other domains. **Without it, we don't have a way to fine-tune new sentence embedding models.** This notebook builds the dataset of sentences to be annotated and used for fine-tuning the sentence embedding model. 

Besides, one would be interested in this notebook in order to reproduce what we did for CORD-19.

**Comment by pafonta** [comment]
In order to keep `notebooks/STS_evaluation.ipynb` but remove Sent2Vec from BBS, what about just:
- adding in the notebook how to install Sent2Vec,
- handling the change of the baseline model when we fine-tune a new sentence embedding model?

**Comment by pafonta** [comment]
As agreed, @FrancescoCasalegno, I will push a commit here for `notebooks/STS_evaluation.ipynb`.

I will do it tomorrow. Indeed, I will check that the modifications are working which needs some time.

**Review by jankrepl — APPROVED** [review]
Nice jobs! I went through the code and did not find any problems with it:)

**Pull request merged**
